---
name: Task Cafe
version: 1.0.8
url: https://github.com/samrocketman/addons-homeassistant/tree/main/taskcafe
slug: taskcafe
description: >-
  More advanced multi-user task management in a Trello-like style but local
  only to Home Assistant.
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
panel_icon: mdi:coffee-to-go-outline
panel_title: Task Cafe
# required by s6 overlay
# https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/
init: false
